### ISSUE TITLE
Get rid of Notification struct

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#18]
I'm sure I'm being entirely dense here, so forgive me, but it seems like the Notification struct is redundant.  It's not an object that's created with a global scope, and we only create it to pass it into either postNotification or NotificationObserver, neither of which are going to be in the same function anywhere but a test class.

So instead of this:

```Swift
let notification = Notification<TestValue, TestSender>(name: "NotificationName", sender: TestSender())
var observer: NotificationObserver? = NotificationObserver(notification: notification,
```

couldn't we just do something like this:

```Swift
var observer: NotificationObserver? = NotificationObserver<TestValue, TestSender>(name: "NotificationName", sender: TestSender(),
```

**Comment by jessesquires** [comment]
Thanks @grosch ! :smile: Definitely some good points.

>It's not an object that's created with a global scope

Why not? There's no reason a `Notification` couldn't be a global constant. Traditionally in ObjC, it's common to define global strings, `static NSString * const kMyNotification`.

But, if you have a specific `sender` instance, then a global definition probably isn't a good idea. So :+1: 

>we only create it to pass it into either `postNotification()` or `NotificationObserver`

Correct. Also a good point. However, I would argue that `Notification` helps reduce *some* duplication and helps provide a more cohesive API. Generally, if I see 2 (or *N*) values moving around together, I package those into a new object (or in Swift, a struct) — which I think is a better design. Really, `Notification` is a fancy tuple, that's all.

-----------------------

It's not expensive to create a `Notification`, so I think the primary argument here would be against the extra "boilerplate" of creating a `Notification` — but I think this is offset by clarity and readability (and the possibility to create a global notification if you want).

**Comment by grosch** [comment]
You raise good points.  I already have my global Notification struct class which just has 'static let' strings in it for the notification names.  I guess those could just instead be your Notification object since it's very little memory.

That, of course, will lead to my next suggestion I'm opening :)
