### ISSUE TITLE
"Notification" should have "observe"

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#21]
Ok, this is my last suggestion.  Not giving a pull request for this because I'm not sure how to code it into the test cases.   Anyways...I think we need these two methods in Notification as well.  I want to observe my notification, and it feels much more natural to have an observe method there than to have to call some other class and pass it this.  

```Swift
public func observe(handler: NotificationObserver<Value, Sender>.ValueSenderHandler) -> NotificationObserver<Value, Sender> {
    return  NotificationObserver(notification: self, handler: handler)
}

public func observe(handler: NotificationObserver<Value, Sender>.NotificationHandler) -> NotificationObserver<Value, Sender> {
    return  NotificationObserver(notification: self, handler: handler)
}
```

You'd use like so then:

```Swift
let notif = Notification<Void, AnyObject>(name: "Notification")
let observer = notif.observe { (value, sender) in
    ....
}
```

It just feels a little more OO to me.

**Comment by jessesquires** [comment]
Thanks again @grosch! :+1: 

I think we start to get into trouble here. Now we've interleaved these 2 distinct types with distinct responsibilities. I think keeping these 2 types provides a clear separation of concerns.

However, you should be able to write your own `extension` to do this. :smile: 

>It just feels a little more OO to me.

A goal of this library is to be *more functional*, and *less* OO.
