### ISSUE TITLE
Should we have a withSender() method?

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#22]
If I want to have a notification that posts with a sender, the way it's currently written I don't think I can have a global Notification property for it as I can't initialize with the sender.  So I have this in my global struct for notifications:

```Swift
struct Notifications {
    ...
    static let MatchWinnerSpecified = Notification<[String : Player], Match>(name: "com.gargoylesoft.Brackets:Match Winner Specified")
}
```

And now when I want to post, I would end up doing something like so:

```Swift
let notif = Notifications.MatchWinnerSpecified
notif.sender = self
notif.post(userInfo)
```

which of course fails, because sender is immutable. 

In a functional model, shouldn't there be a withSender(sender: AnyObject) method that returns a new Notification of the same type, but with the sender set?  Then I'd end up doing:

```Swift
Notifications.MatchWinnerSpecified.withSender(self).post(userInfo)
```

I'm still trying to wrap my brain around functional programming so sorry if I'm missing the mark here.  All of your examples/tests have the sender/receiver in the same method.

I think it would just mean that we add this method to the Notification struct:

```Swift
public func withSender(sender: Sender) -> Notification {
    return Notification(name: self.name, sender: sender)
}
```

**Comment by jessesquires** [comment]
Hey @grosch :smile: Really happy to have your suggestions. Keep them coming :+1: 

Great idea. Totally valid use case. So far in my projects, I've had very simple uses for this library (usually without a specific sender), so I'm really glad to see you finding issues that need to be solved! :clap: 

Your suggestion is *almost* there.

First, we need to change the sender property to make **only the setter** private. 
```swift
private(set) var sender: Sender?
```

Then, as you suggest, `withSender()` would become:

```swift
public mutating func withSender(sender: Sender?) -> Notification {
    self.sender = sender
    return self
}
```

(And let's also make it optional to allow clients to set to `nil`)

-----------------------

Let me know if you'd like to submit a PR! If so, we'll need unit tests for this too. Please follow existing style/patterns :smile:

**Comment by jessesquires** [comment]
Oh -- if you hadn't noticed, 3.0.0 is out. So be sure to pull the latest changes before starting on this.

After this is done, I'll release 3.1.0

**Comment by grosch** [comment]
I’m new to github, though I use git.  To do the first update I made a fork, cloned that, and then sent you a pull request.  

With this new feature, I’m not sure how to tell my personal fork to ‘update’ to look like your version again.  Obviously deleting my repository and forking again would work, but that seems heavy handed.

I also just discovered your https://github.com/jessesquires/HowToContribute <https://github.com/jessesquires/HowToContribute> link so I’ll follow those requests as well this time.

**Comment by grosch** [comment]
Never mind, just figured out how to update my fork.

**Comment by jessesquires** [comment]
@grosch :+1: :smile:

**Comment by jessesquires** [comment]
@grosch - done!

Again, really sorry about the complications with the PR! git is hard sometimes. :smile: 

I really appreciate your interest in the project!

**Comment by jessesquires** [comment]
`3.1.0` is out!

**Comment by grosch** [comment]
Not according to cocoa pods.
