### ISSUE TITLE
Notification shouldn't be mutating

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#26]
So here's a thought.  withSender() is currently a mutating function.  I think instead it should be functional where it returns a new instance.  The issue I'm hitting is my notifications are defined as 'static let' members of a global Notifications struct.  

When I later try to do 

```Swift
Notifications.MyNotification.withSender(self).....
```

I get a compiler error because MyNotification is a 'let', whereas the withSender tried to modify it.

Thoughts?

**Comment by grosch** [comment]
Yah, it's definitely broken as-is.  If I make those 'var' and do posts, I'm getting incorrect objects posting.  If I locally make it return a new Notification, then everything posts as expected.

**Comment by jessesquires** [comment]
Doh. :confounded: 

Very good point. Let's make this change as you suggest.

Unfortunately it's a breaking change. So we'll have to bump to 4.0.

**Comment by jessesquires** [comment]
Thanks @grosch ! :smile:

**Comment by jessesquires** [comment]
Hey @grosch - sorry this took so long. Just pushed 4.0.0 to cocoapods.

I know we had git troubles with your last PR, but please don't let this discourage you from contributing! :smile: You've got great ideas!
