### ISSUE TITLE
typealiases for common notification types

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#28]

**Comment by grosch** [comment]
I think we should add this to the Notification.swift file as it's going to be the most common case:

```Swift
typealias BroadcastNotification = Notification<Any?, AnyObject>
typealias BroadcastObserver = NotificationObserver<Any?, AnyObject>
```

**Comment by jessesquires** [comment]
Thanks @grosch ! :smile: 

* For the first two — I'm not so sure. That seems to encourage loose typing, which is kind of an anti-goal of the library :grin: Or... am I missing something? What's the reasoning behind these?

* For the Cocoa notifications :+1: I agree that these are probably common enough to include in the library. For naming, I'd prefer `CocoaNotification` and `CocoaObserver`.

**Comment by grosch** [comment]
The first two are for the common scenario where you're just saying "X happened" but you aren't passing any data with it.

**Comment by grosch** [comment]
OK, so now I'm leaning to this:

```Swift
typealias BroadcastNotification = Notification<Any?, AnyObject>
typealias BroadcastObserver = NotificationObserver<Any?, AnyObject>
typealias BroadcastHandler = BroadcastObserver.ValueSenderHandler

typealias CocoaNotification = Notification<Any, AnyObject>
typealias CocoaObserver = NotificationObserver<Any, AnyObject>
typealias CocoaHandler = CocoaObserver.NotificationHandler
```

because I have two Cocoa notifications that will run the same code, and it was annoying trying to figure out what the signature was to use for the handler I created.
