### ISSUE TITLE
Add ability to register/unregister via listener class

### ISSUE THREAD

**Issue by ldiqual** [jessesquires/JSQNotificationObserverKit#29]
The neat thing about NSNotificationManager is that I can do this:

```
class ViewController: UIViewController {
    override func viewDidLoad() {
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "onNotification:", name: "Notification", object: nil)
    }

    deinit {
        NSNotificationCenter.defaultCenter().removeObserver(self, name: "Notification")
    }
}
```

Which, instead of providing an observer token, allows to unsubscribe by just specifying `self`. I really like this pattern because I don't have to store the observer token somewhere and unregister later using that token.

What I'd love to see is this:

```
NotificationObserver.register(self, notification: notification) { value, sender in
    // ...
}

NotificationObserver.unregister(self, notification: notification)
```

instead of

```
self.observer = NotificationObserver(notification: notification) { (value, sender) in
    // ...
}

// Somewhere else
observer = nil
```

What do you think about this pattern? Any chance it could be implemented easily?

**Comment by jessesquires** [comment]
Thanks @ldiqual ! :smile: 

This would definitely work! But it feels like stylistic differences more than anything else.

The library's current design vs. your suggestion:
- Both still require 2 calls to register/unregister
- The library requires storing the observer, but your suggestion needs to store the `notification`

One benefit of the library's solution: if you forget to set the observer to `nil`, it would happen implicitly when it's owner is destroyed.

Stylistically, I prefer the `observer` / `nil` pattern. (Obviously :grin:)

**Comment by grosch** [comment]
If you wanted to do that, there'd be no point to this set of classes.  The main benefit to this, over NSNotificationCenter directly, is that you don't have to remember to unregister your observers.  If you want to explicitly unregister them, why use these classes at all, @ldiqual ?

**Comment by jessesquires** [comment]
Another great point from @grosch !

Going to close this out. :smile:

**Comment by ldiqual** [comment]
@jessesquires You don't have to keep a reference on the notification object if you want to unregister `self` from all notifications. So there's no equivalent of 

```
notificationManager.removeObserver(self)
```

with this library. I use this pattern a lot because I don't have to store a reference to `notification` in `self`, and all I need to do is call `removeObserver(self)` in `deinit`.

@grosch I'd argue that the main benefit of JSQNotificationObserverKit is type-safety. Automatic unregistration is a plus, but quite frankly it seems more error prone to have something that unregisters automatically if you don't save a token or assign it to a weak property, than having an observer that you have to manually unregister.

Anyway, thanks for your comments! I understand that my proposal is not the architecture that was in mind during the creation of the library and that the pattern I use might not fit most usages. I'll probably go ahead with a custom solution to my issue (type safety, no token saving).
