### ISSUE TITLE
withSender() doesn't impact observer

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#30]
It's not currently possible to listen for notifications against specific objects.  When I create my NotificationObserver I pass in a Notification object, which was pre-configured with a sender...which likely isn't the REAL sender. 

I need some way, when creating the observer, to tell it which object to really listen for, and not use the one from the Notification object.

I think this is similar to how we added a withSender() function on Notification, but I'm not entirely sure, which is why I'm not giving you an pull request for code.

**Comment by jessesquires** [comment]
Hey @grosch :smile: 

Not sure I follow you... can you give an example? 

The `Notification` and `Observer` both specify the *type* of the sender — which is all that should matter. When the `Observer` receives the actual `Notification` (i.e., in the closure), then it can query the specific sender *instance*.

**Comment by grosch** [comment]
When you "addObserverForName" you can pass in an object, and you only receive notifications if the object matches.  You're automatically registering with the 'sender' parameter of the notification object...which might not be the real sender, or even the thing you want to register against.

**Comment by jessesquires** [comment]
@grosch - Correct, so when you init `NotificationObserver`, the notification you pass should contain the appropriate sender instance, if any.

```swift
// global somewhere
let notification = Notification<MyData, MyViewController>(name: "MyNotif") // sender is nil

// somewhere else
// add specific sender instance
observer = NotificationObserver(notification: notification.withSender(self)) { (value, sender) in
    // handle notification
}

// somewhere inside MyViewController
notification.withSender(self).post(data)
```

**Comment by grosch** [comment]
Argh.  OK, that makes sense, but I'm back again to your interface is too cumbersome now.  With your way I have to do this, which you can't even fully read here because it's going to scroll horizontally 

```Swift
observer = NotificationObserver(notification: Notifications.MatchStateChanged.withSender(match)) {
```

if you put in the convenience funcs I suggested before, that's a much simpler and easier to read:

```Swift
observer = Notifications.MatchStateChanged.onPostFrom(match) {
```

Which makes more sense, and it going to be WAY easier to read/maintain in 6 months when you come back to this code?

I know you're calling "functional" and all here, but I don't think that works for these more complex use cases.   I have this as an extension now in any project I'd use with this library

```Swift
extension Notification {
    func onPost(handler: NotificationObserver<Value, Sender>.ValueSenderHandler) -> NotificationObserver<Value, Sender> {
        return NotificationObserver(notification: self, handler: handler)
    }

    func onPostFrom(sender: Sender, handler: NotificationObserver<Value, Sender>.ValueSenderHandler) -> NotificationObserver<Value, Sender> {
        return NotificationObserver(notification: self.withSender(sender), handler: handler)
    }

    func onCocoaPost(handler: NotificationObserver<Value, Sender>.NotificationHandler) -> NotificationObserver<Value, Sender> {
        return NotificationObserver(notification: self, handler: handler)
    }
}
```

**Comment by jessesquires** [comment]
I can definitely see how the verbosity is undesirable. I agree this can be better. There's no need to say "notification" so many times. 

How about:

1. Rename `NotificationObserver` --> `Observer`
2. Drop the `notification:` label from `init`

then, your example becomes:

```swift
observer = Observer(Notifications.MatchStateChanged.withSender(match)) {
```

**Comment by grosch** [comment]
I don't like the rename idea.  What's an Observer?  There are many types possible, and it'll lead to confusing code down the road.

At the end of the day, a NotificationObserver is useless without a Notification object and vice-a-versa.  I'm not seeing any value in trying to create such a strong barrier between the two.

But also, it's your library, and like you said, I can add the extensions.  I just think this'll be easier for people with less knowledge on how to do that themselves.

**Comment by jessesquires** [comment]
@grosch -- All good points! :+1: 

Not 100% sure what I want to do, but I'll keep this feedback in mind! :smile:
