### ISSUE TITLE
Doesn't work in Swift 3

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQNotificationObserverKit#36]
I'm converting my project to Swift 3 and there's now a conflict because Foundation includes a "Notification" struct already since they renamed NSNotification to Notification.

**Comment by jessesquires** [comment]
Thanks @grosch ! 😄 

Yes, I'm aware of this. I'm going to be deprecating this library. Swift's new `Notification` value type isn't *exactly* like the one provided here (it's not generic), but it's close enough to obsolete this library.
